spring:
  h2.console.enabled: true
  h2.console.path: /h2
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  jpa.hibernate.ddl-auto: create-drop
  datasource:
    url: jdbc:h2:file:C:/Users/kumarh14/Documents/Hemanth;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: pa
    initialization-mode: embedded